### ISSUE TITLE
404 error on create PaymentIntent endpoint 

### ISSUE THREAD

**Issue by sFrady20** [duffelhq/duffel-api-javascript#324]
I was receiving a 404 when using `duffel.paymentIntents.create` on @duffel/api version 1.7.0 and 1.7.1

I looked up the endpoint that was being called here and it was set to 'air/payments/payment_intents'
The documentation says to go directly to `/payments/payment_intents` and so I added `duffel.paymentIntents.path = "payments/payment_intents";` to my server code right before `duffel.paymentIntents.create` and it works now

it looks like some of the other endpoints also have "air/" in them but work properly so I don't know if this is a javascript library issue or an api issue but it was blocking me from taking orders.

**Comment by lapa182** [comment]
Thanks for reporting, @sFrady20! Will take a look at what's going on.

**Comment by lapa182** [comment]
Could you check the latest version and see if you still get 404? As pointed out we wrongly add `air` into the payment_intents path.

**Comment by lapa182** [comment]
Closing the issues as we deployed a fix in the latest version. If it's still an issue, please feel free to re-open!

**Comment by sgerrand** [comment]
📝 This bug was fixed by @lapa182 in the linked pull request above and released in [v1.7.2](https://github.com/duffelhq/duffel-api-javascript/releases/tag/v1.7.2).
