### ISSUE TITLE
TS2307: Cannot find module 'Client' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Rahat47** [duffelhq/duffel-api-javascript#372]
Hi, 
I have been trying to use the SDK with my firebase Cloud Functions,

I have initialized and exported a new instance of Duffel
```
import { Duffel } from '@duffel/api';

const duffel = new Duffel({
    token: 'duffel**********************************4J-o3',
});

export default duffel;
```

which I was using on an express request handler,

```
const airports = await duffel.airports.list({
        limit: 100,
 });
```

but when building and testing the code, 
I am getting this error

```
node_modules/@duffel/api/dist/types/index.d.ts:1:36 - error TS2307: Cannot find module 'Client' or its corresponding type declarations.

1 import { Client as Client$1 } from 'Client';
```

Is this a bug with the SDK or something is wrong on my end

**Comment by go1t** [comment]
Hi, 

Thank you for reaching out. it is indeed a bug in the SDK. We are working on the fix and it should be resolved soon.

You can use v1.7.3 for the time being. Sorry for the inconvenience!

**Comment by lapa182** [comment]
Hi @Rahat47, we deployed a fix for the issue you reported in the latest version (https://github.com/duffelhq/duffel-api-javascript/releases/tag/v1.7.7). Thanks for reporting it and please let us know if you encounter any more issues.
