### ISSUE TITLE
TypeError: url__WEBPACK_IMPORTED_MODULE_1__.URL is not a constructor

### ISSUE THREAD

**Issue by iamcharlesb** [duffelhq/duffel-api-javascript#442]
Hi Team,

I' am getting the below error, please help. BTW I love your product so much!

      const duffel = new Duffel({
        // Store your access token in an environment variable, keep it secret and only readable on your server
        token: 'My Token,
      });
      
      const offerRequestResponse = await duffel.offerRequests.create({
        slices : [
          {
            origin: "NYC",
            destination: "ATL",
            departure_date: "2022-06-21"
          },
          {
            origin: "ATL",
            destination: "NYC",
            departure_date: "2022-07-21"
          }
        ],
        passengers: [{ type: "adult" }, { type: "adult" }, { age: 1 }],
        cabin_class: "business",
        return_offers: true
      })
      
      console.log(offerRequestResponse.data.id);

**Comment by iamcharlesb** [comment]
Error which I' am receiving on my end

<img width="645" alt="image" src="https://user-images.githubusercontent.com/5390172/160250874-630b8b48-d8f2-4d50-8a14-f7f738c13115.png">

**Comment by lapa182** [comment]
Hello @iamcharlesb and thanks for reporting the issue! Just a quick question, are you using the SDK on the client-side or server-side?

**Comment by lapa182** [comment]
Will be closing the issue as there was no update in the last 29 days. If you have any other questions, please feel free to re-open the issue!

**Comment by iamcharlesb** [comment]
Hello Igo,

Iam using the SDK on the client side. Sorry for the delayed response.

Regards,
Charles

**Comment by Lukem121** [comment]
I had the same issue. 

I was using: 
https://github.com/t3-oss/create-t3-turbo

But when I used the non turbo reop it worked:
https://github.com/t3-oss/create-t3-app

Not sure why.

**Comment by iamcharlesb** [comment]
Thanks Luke
