### ISSUE TITLE
Usage Questions

### ISSUE THREAD

**Issue by danshev** [duffelhq/duffel-api-javascript#478]
**Greetings,**

I'm unable to find the answer to these two questions in Duffel's documentation:

1.  How long should one wait between creating an OfferRequest (i.e., `offerRequests.create`) and reviewing/listing offers (i.e., `offers.list`)?  I'm asking largely because [this part of the documentation](https://duffel.com/docs/api/overview/response-times) mentions response times + the fact that Duffel acts as proxy.

2. Somewhat linked to the above question -- [this documentation](https://duffel.com/docs/guides/quick-start#searching-for-flights) mentions a `return_offers` argument ... what is the purpose of that argument?  If set to `true` will offers immediately be returned (eliminating the need to use `offers.list`)?

Thank you

**Comment by joladev** [comment]
Hey there!

1. Once the offer request call has finished you should be able to list the offers, this means you need to await the first one before you can make the second call.
2. That is correct, setting it to `true` means the call returns all the offers. Setting it to `false` means you can paginate and filter the results while the `true` means you just get all of them immediately (which can be a lot of offers!)

**Comment by danshev** [comment]
Great stuff -- thank you very much!

**Comment by sgerrand** [comment]
Closing this as I think all of the questions have been answered.
