### ISSUE TITLE
Suggestion: Get flight fare rules using fare basis code

### ISSUE THREAD

**Issue by abiodunt97** [duffelhq/duffel-api-javascript#606]
It would be very useful to be able to obtain the detailed fare rules such as penalties, seating policies, refund policies etc by providing the fare basis code.

**Comment by go1t** [comment]
Thank you for the suggestion, @abiodunt97. We will pass this along to the team for future consideration!

**Comment by igorp1** [comment]
I confirmed your feedback was captured by our product team @abiodunt97! Closing the issue for now.
