### ISSUE TITLE
Create Duffel App

### ISSUE THREAD

**Issue by simonhlee97** [duffelhq/duffel-api-javascript#648]
Trying to find instructions on how to use the CLI tool. (how to generate a new app?). Is there a boilerplate or example repo available on Github? Thanks in advance.

**Comment by shaundon** [comment]
Hey Simon – you might find our [Create Duffel App](https://duffel.com/docs/developer-tools/create-duffel-app) tool useful for this – it sets up a boilerplate app that connects to Duffel using the Node SDK found in this repo.
