### ISSUE TITLE
`max_connections` is missing from type `CreateOfferRequest`

### ISSUE THREAD

**Issue by nathanlindsay** [duffelhq/duffel-api-javascript#656]
If I give `duffel.offerRequests.create` a `max_connections` value it works but I get a type error:

```typescript
const { data } = await duffel.offerRequests.create({
    ...
    max_connections: 0 // <-- this shows a type error
});
```

I'd make a PR for this but given the problems we had with #653 I thought it would just be easier to make this issue.

**Comment by shaundon** [comment]
Hey – thanks for this, we're very happy you're helping us find and fix issues! We've just released `v1.19.0` which contains this fix.
