### ISSUE TITLE
return_offers question

### ISSUE THREAD

**Issue by LastxTemplar** [duffelhq/duffel-api-javascript#699]
Hi,
I am using the `return_offers` flag for an offers request. I find the response odd in these cases:
when `flag is true` I only usually receive around 20 offers, when setting it as `false` and the querying the offers list request with the offer id I get more than 100 offers in total.
Is this something that is done on purpose while using the test data or am I doing something wrong? I would expect to receive all offers if the `return_offers` flag is true

Thank you!

**Comment by go1t** [comment]
Hi, thanks for reaching out. The behavior you described is not expected I think. 

Would you be able to provide the request ids for both cases? You can find this under `response.headers['x-request-id']`.

**Comment by igorp1** [comment]
@LastxTemplar, I'm doing some cleanup so I'll close this at it seems resolved but please let us know if there's anything else we can help with!
