### ISSUE TITLE
Selected service ID is not the valid one when reaching orders.create()

### ISSUE THREAD

**Issue by godoyLeonardo** [duffelhq/duffel-api-javascript#710]
Hi! 

A part of the implementation that was previously working and is no longer working is the selection of services, specifically baggage. 

```BASH
meta: { status: 422, request_id: 'F1FXLmKy-Q5QFmIAb2yB' },
errors: [
     {
       	type: 'validation_error',
       	title: 'Linked record(s) not found',
      	source: [Object],
     	message: "Field 'id' contains ID(s) of linked record(s) that were not found in your account",
    	documentation_url: 'https://duffel.com/docs/api/overview/errors',
   		code: 'not_found'
	}
]

```

Since we call the GetOffer endpoint multiple times to check that the flight is still available, it is understandable and to be expected that the ID of the services will change. The problem is that in this case, when doing the retrieval of selected services, we are using the last Offer received with its corresponding services. 

In this case, the services to be added to the booking are: 

```TS
 [{"id":"ase_0000AU9mw1Siuc9ifftYY7","quantity":3}]
```
Below, in order of extraction, are all the services that we received in the Offers. The last one would be the GetOffer before CreateOrder(), and, consequently, the Offer.services that we use to obtain the ID to use in this flight. 

```TS
[
  [
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "72.67",
      "segment_ids": [
        "seg_0000AU9mYFlZSEOU53adhG",
        "seg_0000AU9mYFlZSEOU53adhI"
      ],
      "passenger_ids": ["pas_0000AU9mYDWFoCxB6yPNXn"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 23,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mq2Jgp5UJaDobSa"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "61.31",
      "segment_ids": [
        "seg_0000AU9mYFlZSEOU53adhG",
        "seg_0000AU9mYFlZSEOU53adhI"
      ],
      "passenger_ids": ["pas_0000AU9mYDWFoCxB6yPNXn"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 15,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mq2Jgp5UJaDobSb"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "36.32",
      "segment_ids": [
        "seg_0000AU9mYFlZSEOU53adhG",
        "seg_0000AU9mYFlZSEOU53adhI"
      ],
      "passenger_ids": ["pas_0000AU9mYDWFoCxB6yPNXn"],
      "metadata": {
        "type": "carry_on",
        "maximum_weight_kg": null,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 1,
      "id": "ase_0000AU9mq2Jgp5UJaDobSc"
    }
  ],
  [
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "72.67",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 23,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mqOtGGo07agqAN6"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "61.31",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 15,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mqOtGGo07agqAN7"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "36.32",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "carry_on",
        "maximum_weight_kg": null,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 1,
      "id": "ase_0000AU9mqOtGGo07agqAN8"
    }
  ],
  [
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "72.67",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 23,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mviFwbCawxgkYDM"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "61.31",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 15,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mviFwbCawxgkYDO"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "36.32",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "carry_on",
        "maximum_weight_kg": null,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 1,
      "id": "ase_0000AU9mviFwbCawxgkYDQ"
    }
  ],
  [
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "72.67",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 23,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mw1Siuc9ifftYY7"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "61.31",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl" 
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "checked",
        "maximum_weight_kg": 15,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 3,
      "id": "ase_0000AU9mw1Siuc9ifftYY9"
    },
    {
      "type": "baggage",
      "total_currency": "EUR",
      "total_amount": "36.32",
      "segment_ids": [
        "seg_0000AU9mqEdbIBUnebCdsi",
        "seg_0000AU9mqEdbIBUnebCdsl"
      ],
      "passenger_ids": ["pas_0000AU9mqCNDi7CkdDWX4N"],
      "metadata": {
        "type": "carry_on",
        "maximum_weight_kg": null,
        "maximum_length_cm": null,
        "maximum_height_cm": null,
        "maximum_depth_cm": null
      },
      "maximum_quantity": 1,
      "id": "ase_0000AU9mw1Siuc9ifftYYB"
    }
  ]
]
```
In the list I concentrated for better readability all the times we received services, and as you can see the user's selection matches the last Array of available services. 

It should be noted that as booking token for the Order we are using the ID of the last Offer extracted. 

Thanks!

**Comment by igorp1** [comment]
Hey @godoyLeonardo! Sorry for the delayed response here. That's a tough one, thanks for sharing that context! We'd need to dig pretty deep to see what ID caused the mismatch. They will change for every offer and they are specific the combination of passenger and segment. Could I recumbent you to try out using our [ancillaries component](https://duffel.com/docs/guides/ancillaries-component) to generate your order creation payload?

**Comment by godoyLeonardo** [comment]
> Hey @godoyLeonardo! Sorry for the delayed response here. That's a tough one, thanks for sharing that context! We'd need to dig pretty deep to see what ID caused the mismatch. They will change for every offer and they are specific the combination of passenger and segment. Could I recumbent you to try out using our [ancillaries component](https://duffel.com/docs/guides/ancillaries-component) to generate your order creation payload?

Hey! no worries.

At the moment the bug is apparently gone, it only lasted a couple of days and disappeared after I reported it through Slack. 

On the other hand, the component looks quite useful, at least for the seat selection part. Is it expected to be used for other services in the future?

And as far as baggage is concerned, we are already managing it through our own interface, so there are no major problems in that aspect. The only "detail" that I have not been told if you have solved, is the possibility of combining different baggage quantities and services in the same order for the same passenger. This was not possible a few weeks ago as I reported on issue #704.

**Comment by igorp1** [comment]
> At the moment the bug is apparently gone, it only lasted a couple of days and disappeared after I reported it through Slack.

I'm glad it's fixed! And yep, feel free to reach out on Slack too, if you ever get blocked on things. 

> Is it expected to be used for other services in the future?

Absolutely! We've set it up in a way that makes it super easy to add new ancillaries. We'll be adding our [protection product](https://duffel.com/protection) to it very soon. And to opt into it, all you need to. do it specify which services you'd like to display (note the [`services` attribute](https://duffel.com/docs/guides/ancillaries-component#services)). 

>  is the possibility of combining different baggage quantities and services in the same order for the same passenger.

There are constraints around service quantities. You'll find that each of the `offer.available_services` includes a `maximum_quantity`.Also note that services are specific to particular segments and passengers, that's given by the lists `segment_ids` and `passenger_ids`.  So as long as these constraints are respected, you should be able to create an order with any combination of services. Does that make sense? For example...

```
If an offer has the following services:
 
ase_1 -> 15kg checked
ase_2 -> 23kg checked
ase_3 -> carryon 10kg

The only valid combinations are: 

[], [ase_1], [ase_2], [ase_3], [ase1, ase_3], [ase2, ase3]

```
   
I'm gonna close this one up for now. But, of course, please let us know here or on slack if there's anything else we can answer or help with :)
