### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [duffelhq/duffel-api-javascript#713]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by nlopes** [comment]
Hi @igibek,

First of all, thank you for caring about our security.
We have now enabled private vulnerability reporting. Before you report through it, please read our responsible disclosure program documented [here](https://duffel.com/security#responsible-vulnerability-disclosure).

Also, before blindly sending an automatic report generated by a tool, we ask that you first verify if it's valid or not. Sometimes tools do detect non-applicable vulnerabilities.

Thank you!
