### ISSUE TITLE
Typescript Types are not aligned with API docs

### ISSUE THREAD

**Issue by Lukem121** [duffelhq/duffel-api-javascript#782]
"name" is not on the type
![image](https://github.com/duffelhq/duffel-api-javascript/assets/30378184/a2db9823-f2ac-4016-b62f-a90f4ddffcb4)

The type definition
![image](https://github.com/duffelhq/duffel-api-javascript/assets/30378184/6f0075d0-fcea-4e2f-ac6a-47bd7c9528e1)

If I check the docs I see that "query" deprecated.
https://duffel.com/docs/api/v1/places/get-place-suggestions

**Comment by andrejak** [comment]
Thanks for flagging, I'll put up a PR to address that shortly.

**Comment by andrejak** [comment]
I believe this should be [fixed](https://github.com/duffelhq/duffel-api-javascript/pull/783) now, let me know if you continue to have issues (you'll need to update to the [latest version](https://github.com/duffelhq/duffel-api-javascript/pull/784)).
