### ISSUE TITLE
Version 2.5.3: Cannot find module 'types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by BakerSmithA** [duffelhq/duffel-api-javascript#797]
Attempting to build my project with @duffel/api@2.5.3 and TSC version 5.2.2 I'm getting the following errors:

```
node_modules/@duffel/api/dist/typings.d.ts:1288:32 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

1288     import { OrderSlice } from 'types';
                                    ~~~~~~~

node_modules/@duffel/api/dist/typings.d.ts:3767:36 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

3767     import { PaginationMeta } from 'types';
                                        ~~~~~~~

node_modules/@duffel/api/dist/typings.d.ts:3921:12 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

3921     export declare class Airlines extends Resource {
                ~~~~~~~
```

It looks like a few similar issues were recently fixed: https://github.com/duffelhq/duffel-api-javascript/issues/794

Thanks for your support!

**Comment by andrejak** [comment]
Hi, could you tell me a bit more about your project set up, and how you're importing and initialising the library? I currently don't get the same error when I try to build a few of our projects. For now I'm upgrading our TS versions here in case that will help: https://github.com/duffelhq/duffel-api-java%E2%89%88script/pull/798

**Comment by BakerSmithA** [comment]
Hi @andrejak, I tried initialising a new Typescript + NodeJS project (npm version 9.8.1, Typescript 5.2.2, NodeJS 18.18.1), where I also managed to replicate the problem. Here's a link to a repo where you should be able to replicate the issue too https://github.com/BakerSmithA/duffel_type_error

Just to note, I found that I could fix the type errors using `"skipLibCheck": true` in the `tsconfig.json` (although it's obviously preferable to disable this flag).

If there's something else wrong with the setup here that you can see, then that would be great! Thanks!

**Comment by andrejak** [comment]
Thank you for creating the sample repo, that was very helpful. I think I've fixed the issues and I am able to build your example with no errors using the new 2.5.6 version. I'm going to close this for now, but if you still see problem feel free to re-open and tag me :)

**Comment by BakerSmithA** [comment]
Thanks for fixing that, and so quickly! All working from outside now too :)
