### ISSUE TITLE
Type mismatch between documentation and Typescript types

### ISSUE THREAD

**Issue by Tom-Carpendale** [duffelhq/duffel-api-javascript#833]
The docs state that some fields on responses can be null, for example [`penalty_currency` when the change/refund is not allowed](https://duffel.com/docs/guides/displaying-offer-and-order-conditions#:~:text=If%20refunds%20aren%27t%20allowed%2C%20the%20conditions.refund_before_departure.allowed%20attribute%20will%20be%20false%2C%20and%20the%20penalty%20amount%20and%20currency%20will%20be%20null), 

> If refunds aren't allowed, the conditions.refund_before_departure.allowed attribute will be false, and the penalty amount and currency will be null

however the typing for this does not accept this as the case as seen here: https://github.com/duffelhq/duffel-api-javascript/blob/bf086f2d50c261b656f98d8d032455d689221c38/src/types/shared.ts#L143

```ts
/**
 * The currency of the `penalty_amount` as an [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
 * This will be in a currency determined by the airline, which is not necessarily the same as the currency of the order or offer.
 * If this is `null` then `penalty_amount` will also be `null`.
 * @example "GBP"
 */
penalty_currency: string
```

It looks as if recently some changes have been made around this, including making `penalty_amount` nullable, so perhaps some have been missed. https://github.com/duffelhq/duffel-api-javascript/blob/bf086f2d50c261b656f98d8d032455d689221c38/src/types/shared.ts#L150

**Comment by Tom-Carpendale** [comment]
Thank your for the fast fix - it looks good and is working our end now :)

**Comment by igorp1** [comment]
Thanks for confirming @Tom-Carpendale!
