### ISSUE TITLE
import{URL as s,URLSearchParams as e}from"url"

### ISSUE THREAD

**Issue by JisanAR03** [duffelhq/duffel-api-javascript#835]
import{URL as s,URLSearchParams as e}from"url" error showing when trying to compile the code

**Comment by igorp1** [comment]
@JisanAR03, could you share a codesandbox or maybe a repo where you are encountering this issue? With just the information above it's a bit hard for me to help you. More specifically, we can help with some more information like 
- what version of node you are using? 
- how are integrating the library?
- how are you building your code?
- what version of the library are you using?

**Comment by andrejak** [comment]
I'm going to close this issue due to lack of activity, but please let us know if you are still having the problem and we can reopen it.

**Comment by JisanAR03** [comment]
> I'm going to close this issue due to lack of activity, but please let us know if you are still having the problem and we can reopen it.

I'm very sorry for not responding on this issue ,,I will provide the details later ,, for now I just busy with something else
