### ISSUE TITLE
`Airline` interface is missing `conditions_of_carriage_url` field

### ISSUE THREAD

**Issue by Tom-Carpendale** [duffelhq/duffel-api-javascript#878]
The [docs](https://duffel.com/docs/api/v1/offers#offers-schema-owner-owner-conditions-of-carriage-url) specify a field called `conditions_of_carriage_url` on the Airline object, but this is not present in the TypeScript types:

https://github.com/duffelhq/duffel-api-javascript/blob/fa3b2e49ce5badc559589ce9938bda7de04058a8/src/supportingResources/Airlines/AirlinesTypes.ts#L1-L26

**Comment by andrejak** [comment]
Thank you for reporting! I've created PR to fix it here:  https://github.com/duffelhq/duffel-api-javascript/pull/879
