### ISSUE TITLE
Missing `PassengerTitle` enum values

### ISSUE THREAD

**Issue by Tom-Carpendale** [duffelhq/duffel-api-javascript#886]
The [docs](https://duffel.com/docs/api/v1/orders/create-order#orders-create-an-order-body-parameters-passengers-passengers-title) specify 5 possible values for `PassengerTitle`, but the typescript types represent 3 of them in upper and lowercase, and miss the other 2:

https://github.com/duffelhq/duffel-api-javascript/blob/c308b4f761d1fccae03d964fffcabc7efd0ecc36/src/types/shared.ts#L67-L70

**Comment by andrejak** [comment]
Hi @Tom-Carpendale , this should be fixed now after this PR: https://github.com/duffelhq/duffel-api-javascript/pull/887
If you see any issues with it please let us know. Feel free to also submit PRs in the future if it's a simple fix :)
