### ISSUE TITLE
The docs are a bit out of date

### ISSUE THREAD

**Issue by randomprogramming** [duffelhq/duffel-api-javascript#902]
I started reading the documentation here: https://duffel.com/docs/guides/getting-started-with-flights

Looked at the code:
```
duffel.offerRequests.create({
  slices : [
    {
      origin: "NYC",
      destination: "ATL",
      departure_date: "2021-06-21"
    },
    {
      origin: "ATL",
      destination: "NYC",
      departure_date: "2021-07-21"
    }
  ],
  passengers: [{ type: "adult" }, { type: "adult" }, { age: 1 }],
  cabin_class: "business",
})
```

But it seems that this way of searching for flights is not available anymore, now you need to pass in a `Place` for the origin and destination objects.

**Comment by igorp1** [comment]
Hi @randomprogramming, thanks for reaching out. Where did you learn "now you need to pass in a Place for the origin and destination objects"? Please let me know if you've seen that in our documentation so we can correct it. You will find that on the [api reference of the create offer request endpoint](https://duffel.com/docs/api/v1/offer-requests/create-offer-request) slice's origin and destination must be a 3 letter string of the iata code for a city or airport:

<img width="500" alt="Screenshot 2024-04-02 at 09 02 29" src="https://github.com/duffelhq/duffel-api-javascript/assets/2934495/07647206-72d8-4ac9-98b1-2a65b999a766">

The getting started guide seems to agree with that. Please do let me know if there's a mistake on the docs though, so we can correct asap. Thanks!

**Comment by randomprogramming** [comment]
Maybe I am misunderstanding something, but:

<img width="525" alt="image" src="https://github.com/duffelhq/duffel-api-javascript/assets/48063901/19923222-2095-4f30-9606-b830c9cd4b34">

Typescript gives me the error `Type 'string' is not assignable to type 'Place'.ts(2322)
typings.d.ts(1652, 13): The expected type comes from property 'origin' which is declared here on type 'Omit<OfferRequestSlice, "origin_type" | "destination_type">'` for all of these.

**Comment by igorp1** [comment]
Ah I see, you are not misunderstanding it. The types for origin and destination are incorrect. I just opened a PR to correct that. Thanks for letting me know and sorry for the trouble!

**Comment by igorp1** [comment]
PR was just merged @randomprogramming. If you have any trouble please reach out!
