### ISSUE TITLE
Wierd issue with Stays API

### ISSUE THREAD

**Issue by randomprogramming** [duffelhq/duffel-api-javascript#905]
I've been trying out duffel API for some time now, everything seems to be working okay, but today I tried using the Stays API as so:

```
try {
    return await this.duffel.stays.search({
        rooms: 1,
        adults: 2,
        location: {
            radius: 5,
            geographic_coordinates: {
                longitude: 2.4468358606916354,
                latitude: 48.86873001352504,
            },
        },
        check_out_date: "2024-05-01",
        check_in_date: "2024-05-10",
    });
} catch (e) {
    console.log("Error:");
    console.log(JSON.stringify(e));
}
```

And this simply prints out:

```
Error:
{"headers":{}}
```

I tried debugging and looking at the error closely, but there's no helpful information. Not sure what's going on?

**Comment by randomprogramming** [comment]
Hmh. After further reading it seems like Stays is only available for "enterprise" clients? Would love to be able to still access the test data for testing out an MVP without actually having to open a business..

**Comment by igorp1** [comment]
Hi @randomprogramming, to be able to use the Stays API, even in development, you need to [contact us](https://duffel.com/stays) so we can enable it for you. Sorry about the trouble but that's important for us to maintain good relationships with our content suppliers and do our best to understand your use case.
