### ISSUE TITLE
Multi-step search API does not return business or first class BA flights

### ISSUE THREAD

**Issue by BakerSmithA** [duffelhq/duffel-api-javascript#917]
Hi,

The Duffel best practise docs recommended using the multi-step search API. We've developed against that, however, we're not getting any business or first class flights for British Airways in the production environment (they show up in the development environment). 

I've tested to see whether this is an issue with our codebase, however, the same issue is present in the Duffel dashboard:

<img width="600" alt="Screenshot 2024-05-01 at 09 51 44" src="https://github.com/duffelhq/duffel-api-javascript/assets/23617988/4349f7b8-c480-477a-96d3-9098eef93cf9">

BA not listed in available airlines for this route:

<img width="600" alt="Screenshot 2024-05-01 at 09 51 55" src="https://github.com/duffelhq/duffel-api-javascript/assets/23617988/a8503bf7-17db-476e-897c-e653096c076d">

Business class flights are available through BA's website for this route:

<img width="600"  src="https://github.com/duffelhq/duffel-api-javascript/assets/23617988/1defec9c-b915-4a5d-9ba8-0f646fa78671">

I've also tested using the older single-step search API (request below), which does return business class BA flights.

```
curl --location 'https://api.duffel.com/air/offer_requests' \
--header 'Accept-Encoding: gzip' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Duffel-Version: v1' \
--header 'Authorization: Bearer ••••••' \
--data '{
  "data": {
    "slices" : [
      {
        "origin": "LHR",
        "destination": "CPT",
        "departure_date": "2024-05-13"
      }
    ],
    "passengers": [{ "type": "adult" }],
    "cabin_class": "business",
    "max_connections": 0
  }
}'
```

**Comment by jankowiakmaria** [comment]
Hi @BakerSmithA,

Thank you for providing all the details.
Do you mind opening a support ticket with [help@duffel.com](mailto:help@duffel.com) as it's not a javascript client specific issue?
