### ISSUE TITLE
Missing `passenger_ids` in `OrderDocument`

### ISSUE THREAD

**Issue by BakerSmithA** [duffelhq/duffel-api-javascript#931]
The Typescript `OrderDocument` type:

https://github.com/duffelhq/duffel-api-javascript/blob/920405a2a6385cb0355b3677814e74130c3ccaf7/src/booking/Orders/OrdersTypes.ts#L368

is missing `passenger_ids` as described in your API docs:

https://duffel.com/docs/api/v1/orders/schema#orders-schema-documents

Thanks!

**Comment by andrejak** [comment]
Thank you for reporting, this should be added now here: https://github.com/duffelhq/duffel-api-javascript/blob/920405a2a6385cb0355b3677814e74130c3ccaf7/src/booking/Orders/OrdersTypes.ts#L76
