### ISSUE TITLE
Duffel flights with booked seats type not matching `Seat` metadata type 

### ISSUE THREAD

**Issue by Tom-Carpendale** [duffelhq/duffel-api-javascript#945]
When creating an order, you can supply Services, such as baggage or seats. The order will then contain a services field, which is an array of `OrderService`s. These have a `metadata` field, which is typed like so `metadata?: OrderServiceBaggageMetadata | Seat;`. This `Seat` type can be found here: 
https://github.com/duffelhq/duffel-api-javascript/blob/61ef419d1e632f9a3c749b6f968299a433aa57a3/src/booking/Orders/OrdersTypes.ts#L23-L39

However, flights booked that use the Duffel carrier have null for the seat name, e.g.
```json
{
  "segmendIds":["seg_0000Al1UTIYbFWGUecqV5E"],
  "metadata":{
    "disclosures":[],
    "designator":"29B",
    "name":null
  }
}
``` 

I'm not sure if the name should therefore be nullable, or if the Duffel flight orders should have a name provided for the seat services.

Many thanks!

**Comment by andrejak** [comment]
Thank you for reporting, the name is set as nullable now: https://github.com/duffelhq/duffel-api-javascript/blob/16bfff388f84f7d7944dd6ff57588335b22fb3eb/src/booking/Orders/OrdersTypes.ts#L38
